W8D1/RedditClone/RedditClone/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  resources :users
  resource :session
  resources :posts, except:[:index,:new,:edit]
  
  resources :subs do
    resources :posts, only:[:new,:edit, :index, :show]
  end
end

W8D1/RedditClone/RedditClone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :sub
  
  belongs_to :author,
    foreign_key: :user_id,
    class_name: :User

  has_many :PostSubs
end

W8D1/RedditClone/RedditClone/app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :post_id, uniqueness: {scope: :sub_id}, presence: true
  validates :sub_id, presence: true 
  belongs_to :post 
  belongs_to :sub 

end

W8D1/RedditClone/RedditClone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true
  
  belongs_to :moderator,
    foreign_key: :user_id,
    class_name: :User

  has_many :posts
  
  has_one :PostSub

end

W8D1/RedditClone/RedditClone/app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password 

  before_validation :ensure_token 

  has_many :posts,
    foreign_key: :user_id,
    class_name: :Post
  
  has_many :subs,
    foreign_key: :user_id,
    class_name: :Sub

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save 
    self.session_token
  end

  def ensure_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

W8D1/RedditClone/RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #CRLLL 
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_login
    redirect_to new_sesion_url unless logged_in?
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end


end

W8D1/RedditClone/RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to sub_url(@post.sub_id)
    flash[:errors] = @post.errors.full_messages
  end

  def edit
    @post = Post.find(params[:id])

  end

  def update
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id && @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors]=@post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub_id)
  end

  private

  def post_params
    params.require(:post).permit(:title,:url,:content,:sub_id)
  end
end

W8D1/RedditClone/RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user 
      login(@user)
      # redirect_to subs_url
    else 
      flash[:errors] = "No, the coffee in Peru is much hotter"
      render :new 
    end
  end

  def destroy
    logout 
    redirect_to new_session_url
  end
end

W8D1/RedditClone/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login
  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id 
    if @sub.save 
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @subs.errors.full_messages 
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.user_id == current_user.id && @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @subs.errors.full_messages 
      render :edit
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy 
    redirect_to subs_url 
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

W8D1/RedditClone/RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      login(@user)
      redirect_to subs_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new 
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:username, :password)  
  end

end

W8D1/RedditClone/RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

W8D1/RedditClone/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

W8D1/RedditClone/RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
      <form action="<%=session_url%>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input type="submit" value="LogOUT">
      </form>
    <% end %>
    <%= yield %>
  </body>
</html>

W8D1/RedditClone/RedditClone/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

W8D1/RedditClone/RedditClone/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

W8D1/RedditClone/RedditClone/app/views/posts/edit.html.erb
<h1>Edit This Shit</h1>

<form action="<%=post_url(@post)%>"method="post">
  <input type="hidden" name="authenticity_token"value="<%=form_authenticity_token%>">
  <input type="hidden" name="post[sub_id]"value="<%=params[:sub_id]%>"> 
  <input type="hidden" name="_method" value="patch">
  
  <label for="title">Title</label>
    <input type="text"id="title"name="post[title]"value="<%=@post.title%>">
  
  <br>

  <label for="url">URL</label>
    <input type="text"id="url"name="post[url]"value="<%=@post.url%>">

  <br>

  <label for="content">Content</label>
  <br>
    <textarea name="post[content]" id="" cols="30" rows="10" id="content" ><%=@post.content%></textarea>
  <br>

  <input type="submit"value="Edit Post">
</form>
<a href="<%=post_url(@post)%>">Back to work</a>

W8D1/RedditClone/RedditClone/app/views/posts/new.html.erb
<form action="<%=posts_url%>"method="post">
  <input type="hidden" name="authenticity_token"value="<%=form_authenticity_token%>">
  <input type="hidden" name="post[sub_id]"value="<%=params[:sub_id]%>"> 
  
  <label for="title">Title</label>
    <input type="text"id="title"name="post[title]"value="<%=@post.title%>">

  <label for="url">URL</label>
    <input type="text"id="url"name="post[url]"value="<%=@post.url%>">

  <label for="content">Content</label>
    <textarea name="post[content]" id="" cols="30" rows="10" >
      <%=@post.content%>
    </textarea>

  
  <input type="submit"value="Create Post">
</form>

W8D1/RedditClone/RedditClone/app/views/posts/show.html.erb
<h1><%=@post.title%></h1>
<%=@post.url%>
<br>
<%=@post.content%>
<br>
<a href="<%=edit_sub_post_url(@post.sub_id,@post)%>">Edit Post</a>
<br>
<a href="<%=sub_url(@post.sub_id)%>">Back</a>

W8D1/RedditClone/RedditClone/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>